templateArray = ['new entry "Shout_TraceWeapon_TemplateDescription';...
                 'type "SpellData"';...
                 'data "SpellType" "Shout"';...
                 'using "Shout_TraceWeapon"';...
                 'data "Icon" Action_Paladin_SacredWeapon"';...
                 'data "DisplayName" "h08bf2cfeg4d3eg4f8agac64g5622cd9d5551;1"';...
                 'data "Description "h07e76f2agfc64g47f8g97fag5686320718c0;6"';...
                 'data "SpellProperties" "SummonInInventory(407954e3-71e4-4611-9221-0ba3ea71d6e8,2,1,true,true,true,,,REPRODUCTION,REPRODUCTION)"';...
                 'data "SpellFlags" "UNUSED_D"';...
                 ""];

templateFile = templateArray;
for i = 1:1:1998
    for j = 1:1:10
        tempArray = templateArray;
        tempArray(1) = tempArray(1) + i + """";
        writelines(tempArray(j),"Spell_TraceTemplateDescription.txt",WriteMode="append")
    end
end