templateArray = ['new entry "MANABURST_CHANNELING_';...
                 'type "StatusData"';...
                 'data "StatusType" "BOOST"';...
                 'data "Icon" "Spell_Evocation_Sunbeam"';...
                 'data "DisplayName" "hadd9225d80754be8a4940335d532213fe2cg;1"';...
                 'data "Description" "h0317125dd2784509abeef76e6ed9d603ec80;6"';...
                 'data "DescriptionParams" "DealDamage(';...
                 'data "Boosts" "AttackSpellOverride(Zone_ManaBurst_Caliburn, Shout_Charge_ManaBurst);UnlockSpellVariant(not SpellId(Zone_ManaBurst_Caliburn),ModifyUseCosts(Add,ManaBurstLocked,1,0));DamageBonus(';...
                 ""];

for i = 1:1:54
    for j = 1:1:9
        tempArray = templateArray;
        tempArray(1) = tempArray(1) + i + '"';
        tempArray(7) = tempArray(7) + i + ',Radiant)"';
        tempArray(8) = tempArray(8) + i + ',Radiant)"';
        writelines(tempArray(j),"Status_NoblePhantasm.txt",WriteMode="append")
    end
end